apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-fetcher
  name: test-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-fetcher
  template:
    metadata:
      labels:
        app: test-fetcher
    spec:
      containers:
      - image: quay.io/klape/test-fetcher:latest
        imagePullPolicy: IfNotPresent
        name: test-fetcher
