kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: external-secrets-crds
spec:
  project: default
  destination:
    name: in-cluster
    namespace: external-secrets
  source:
    repoURL: https://github.com/kylape/pac-demo.git
    path: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
