kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: external-secrets
spec:
  project: default
  destination:
    name: in-cluster
    namespace: external-secrets
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    path: external-secrets/helm
    targetRevision: v0.10.5
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
