kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: stackrox-policies
spec:
  project: default
  destination:
    name: in-cluster
    namespace: stackrox
  source:
    repoURL: https://github.com/kylape/pac-demo.git
    path: stackrox/policies
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
